### DISCUSSION TITLE
The action 'request' could not be found for Shipit::GithubAuthenticationController

### DISCUSSION THREAD

**Discussion by leonardomgt** [Shopify/shipit-engine#1276] [Q&A]
Hello, community!

I've trying to set up shipit for my organisation, and after doing the setup (created the rails app, created and installed the GitHub App, configured the secrets.yml), when running it locally with `rails server`, it only shows the following message:

![Screenshot 2022-07-22 at 15 07 24](https://user-images.githubusercontent.com/18677926/180462057-383b72b6-bdc8-44d5-861e-00754f6c938f.png)

I can see that, in fact, there is not a 'request' action in `shipit-engine`'s `github_authentication_controller.rb`:
```
# frozen_string_literal: true
module Shipit
  class GithubAuthenticationController < ActionController::Base
    include Shipit::Engine.routes.url_helpers

    def callback
      return_url = request.env['omniauth.origin'] || root_path
      auth = request.env['omniauth.auth']

      return render('failed', layout: false) if auth.blank?

      session[:user_id] = sign_in_github(auth)

      redirect_to(return_url)
    end

    def logout
      reset_session
      redirect_to(root_path)
    end

    private

    def sign_in_github(auth)
      user = User.find_or_create_from_github(auth.extra.raw_info)
      user.update(github_access_token: auth.credentials.token)
      user.id
    end
  end
end
```

My secrets.yml looks like this:

```
development:
  app_name: My Shipit
  secret_key_base: 54566afb...58e60
  host: 'http://localhost:3000'
  redis_url: redis://localhost
  github:
    domain: # defaults to github.com
    bot_login:
    app_id:
    installation_id:
    webhook_secret:
    private_key:
    oauth:
      id:
      secret:
      # team: MyOrg/developers # Enable this setting to restrict access to only the member of a team

test:
  app_name: My Shipit
  secret_key_base: cb8e4f...532dd
  host: 'http://localhost:4000'
  redis_url: redis://localhost
  github:
    domain: # defaults to github.com
    bot_login:
    app_id:
    installation_id:
    webhook_secret:
    private_key:
    oauth:
      id: <%= ENV['GITHUB_OAUTH_ID'] %>
      secret: <%= ENV['GITHUB_OAUTH_SECRET'] %>
      # teams: MyOrg/developers # Enable this setting to restrict access to only the member of a team

production:
  default_merge_method: rebase
  app_name: My Shipit
  secret_key_base: 17b89b81...13af31
  host: https://my-shipit.herokuapp.com
  redis_url: "redis://redis-host"
  github:
    domain: # defaults to github.com
    bot_login: "my-shipit[bot]"
    app_id: XXXXXX
    installation_id: XXXXXXXX
    webhook_secret: cdffcb...f2c2e
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      <the-private-key>
      -----END RSA PRIVATE KEY-----
    oauth:
      id: Iv1.99916XXXXXXXXX
      secret: 8da99f2...24bc4da
      # teams: MyOrg/developers # Enable this setting to restrict access to only the member of a team
  env:
    # SSH_AUTH_SOCK: /foo/bar # You can set environment variable that will be present during deploys.

```

I have also created a heroku app, and pushed the app there, but there the message is the following:
<img width="549" alt="Screenshot 2022-07-22 at 15 42 06" src="https://user-images.githubusercontent.com/18677926/180463706-fe754026-c891-4596-bf6d-8f45a8c59c0c.png">

Am I missing something in the configuration? I still haven't been able to run the app and start creating the Stacks.

Thank you.
