### ISSUE TITLE
Shipit setup: dashboard remains "empty"

### ISSUE THREAD

**Issue by mathieutu** [Shopify/shipit-engine#1266]
Hi!

Firstly, thanks for this software, which looks very promising! 

I'm trying to configure shipit to deploy our stacks.

I've hosted it with success in Heroku. PG database, redis and scheduler are configured and seem to work.
Github connection is ok.

However our **dashboard stays desperately empty**. 😢

<img width="1397" alt="Screenshot 2022-05-19 at 15 36 02" src="https://user-images.githubusercontent.com/11351322/169306642-769baa2b-3311-4286-b560-4de6bac73bcc.png">

Webhooks are properly received (we can see them in logs), and responses are ok (200 or 204 depending if the hook is handled or not), but **nothing is saved in our database**. (all our tables except users, repo and stacks are empty).

No error raised.

I've tried to add a dumb shipit file at the root of one of our repos just to see if anything changes, without any success. I don't see any difference with or without the file (even links, tasks, etc don't show up).

<details>
<summary>`shipit.yml`</summary>

```yml
# WIP under tests by #crew_infra

links:
  acceptance: https://api-acceptance.alan.com
  production: https://api.alan.com

dependencies:
  override:
    - poetry install

ci:
  require:
    - ci/circleci

deploy:
  override:
    - echo "Deploying to production!"
    - echo $RUN_MIGRATIONS
    - echo $REGION
  variables:
    - name: RUN_MIGRATIONS
      title: Run database migrations on deploy
      default: 1
    - name: REGION
      title: Run a deploy in a given region
      select:
        - east
        - west
        - north
tasks:
  restart:
    action: "Hello World!"
    description: "Just log a message"
    steps:
      - echo "Hello World!"

review:
  checklist:
    - >
      Do you know if it is safe to revert the code being shipped? What happens if we need to undo this deploy?
    - Has the Docs team been notified of any major changes to the app?
    - Is the app stable right now?

  monitoring:
    - image: https://static.alan.com/fr-web/acceptance/0b513158d70643edcc0db7b7c501ee4f5c8390d6/waving.45acf207ff947eec939bc15905482e85.svg
    - iframe: https://acceptance.alan.com/
```

</details>

Do you have any idea or hints that can help us?

Thank you.
