### ISSUE TITLE
Feature request: Config inheritance

### ISSUE THREAD

**Issue by benlangfeld** [Shopify/shipit-engine#1390]
ShipIt [currently implements](https://github.com/powerhome/shipit-engine/blob/a6f1948622f6f76e4b6d61fb4f1b2e90dd9fe680/app/models/shipit/deploy_spec/file_system.rb#L106-L120) replacement config files [on a per-environment basis](https://github.com/powerhome/shipit-engine/blob/a6f1948622f6f76e4b6d61fb4f1b2e90dd9fe680/README.md?plain=1#L129-L131). This is useful when configuration is significantly different between environments.

When configuration differences are limited between environments, this can result in significant duplication. It would be useful for the more specific files to be able to contain an inheritance directive to reduce this duplication. This might look something like this:

shipit.production.yml:
```yaml
inherit_from: shipit.yml

machine:
  environment:
    PUBLIC: true
```

shipit.yml:
```yaml
machine:
  environment:
    PUBLIC: false

deploy:
  override:
    - ./some_deployment_process.sh ${PUBLIC}

...more shared stuff...
```

We'd be willing to contribute this upstream if it has a reasonable change of being merged. Looking for in-principle approval of a feature like this from a maintainer.
