### ISSUE TITLE
NoMethodError: undefined method `review_checklist' for nil:NilClass

### ISSUE THREAD

**Issue by drdee** [Shopify/shipit-engine#292]
When trying to deploy [Trekkie](https://shipit.shopify.com/shopify/trekkie/production/deploys/new?sha=ba91a4ef267890ecda6e673fc4e3922768231b61), I get the following error:

NoMethodError: undefined method `review_checklist' for nil:NilClass

Which means that `cached_deploy_spec` is nil (see https://github.com/Shopify/shipit2/blob/ba876d90c8d399dbf6a1a88231d14a24f5c9e8ee/app/models/stack.rb#L182)

Full stacktrace: 
https://exceptions.shopify.com/apps/53333766b74f334f6c000379/errs/54af0177b74f33362c000edb

The shipit.yml is as follows:

``` yml
deploy:
  override:
    - bundle exec ejson decrypt config/secrets.production.ejson > config/secrets.production.json
    - bundle exec rake assets:upload
rollback:
  override:
    - bundle exec rake assets:rollback
```

/cc @yagnik
