### ISSUE TITLE
Treat Heroku as first-class citizen

### ISSUE THREAD

**Issue by gmalette** [Shopify/shipit-engine#297]
Making Heroku first-class has many advantages. We could support a default set of tasks, checklist, fetch script, visualizations, etc. We could have interfaces to set the config values.

The current `shipit.yml` for Heroku projects looks like:

``` yml
dependencies:
  override: []

deploy:
  override:
    - push-to-heroku my-awesome-app
```

I suggest

``` yml
heroku:
  name: my-awesome-app

# heroku: my-awesome-app
```
