### ISSUE TITLE
Command overrides should always be treated as string

### ISSUE THREAD

**Issue by byroot** [Shopify/shipit-engine#346]
``` yaml
deploy:
  override:
    - true
```

Will obviously be parsed as `true` not `"true"`, which breaks shipit.

cc @graemej
