### ISSUE TITLE
Inquiry: How do you use ShipIt internally with API/E2E tests?

### ISSUE THREAD

**Issue by lanceblais** [Shopify/shipit-engine#515]
Hello,

I wasn't sure how else to reach out, please let me know if there's a better way.

The way I understand the workflow with ShipIt is that each repository contains a `shipit.yml` file describing what steps are performed to deploy the repository.

How are you fitting in API and End-to-End tests into Shipit?

We have multiple repositories that get deployed. Once the code is live, we run API tests and if successful, End-to-End tests. 
Right now, our deploys are blocked until the End-to-end tests pass (i.e. no other repository can go out to $ENV until the End-to-End tests are green).

If we moved to ShipIt, how would this work?

**Comment by byroot** [comment]
Hi,

To re-implement your flow with shipit you would need to consider those tests as part of the deploy:

```yaml
# shipit.yml

deploy:
  override:
    - script/deploy # or cap / fab / whatever
    - script/api-tests
    - script/end-to-end-tests
```

If any of those 3 commands fail, shipit will immediately stop the current deploy.

What you might want thought is to trigger a rollback if it happens. We don't have automatic rollbacks on failure, but it's could be easily implemented.

Does that answer your question?
