### ISSUE TITLE
Allow custom env per stack

### ISSUE THREAD

**Issue by teu** [Shopify/shipit-engine#530]
Currently facing a problem in which we would like to have  an effective rollback. 

Our cycle in short:
* capistrano builds [datetime]_[short tag].tgz artifact
* capistrano sends artifact to s3
* capistrano uploads a deployment script to all machines
* machine fires script to download and install artifact

The only way I see to rollback quickly with shipit is to simply redeploy and make capistrano assess if the artifact is in s3 first. This however creates a problem in which we don't have the option to force re-build the already deployed commit (in case of build problems that went on production) and once built it will always download this specific artifact as there is no way to pass any information to capistrano via shipit aside the environment.
 
Allowing custom environments per stack could open a whole range of possibilities. A simple K/V setting of ENV vars per stack would allow us to directly influence what is being deployed. 

Additionally shipit could pass the TIMESTAMP of the initial and last deployment of the specific branch, as I suspect this is already in the database anyway.

**Comment by byroot** [comment]
Per stack? Or per deploy?

If you want some env to be set for all the commands run for a stack there is this: https://github.com/shopify/shipit-engine#environment

If you want to set environment variables for a specific deploy there is that feature (Just noticed it is undocumented, I'll fix that):

```yaml
deploy:
  variables:
    -
      name: REBUILD
      title: Force artifacts rebuild
      default: '0'
```

Which prompts you before deploy with this:

<img width="512" alt="capture d ecran 2016-02-19 a 10 08 56" src="https://cloud.githubusercontent.com/assets/44640/13179205/e30b42d4-d6f0-11e5-9306-3faaaae2432b.png">


> Alternatively shipit could pass the TIMESTAMP of the initial and last deployment of the specific branch

Not sure if it would work for you, but we already pass the last deployed SHA:
https://github.com/shopify/shipit-engine#script-parameters

**Comment by teu** [comment]
Excellent! Thanks!

**Comment by byroot** [comment]
Closing this assuming it fulfill your need. Feel free to re-open if it turns out it's not.

**Comment by teu** [comment]
One problem we are facing is multiple stages of development. This is more a shipit.yml-per-stack problem or perhaps per env settings. As we would deploy pre production envs continuously, the standards variables would need to change in some cases - this could be solved via some capistrano hack but then again the flexibility of the vars would be lost.

**Comment by byroot** [comment]
Oh. You have a feature for that, you can have multiple `shipit.yml`

For example if you have a stack like: `SomeOrg/SomeRepo/staging`, shipit will first look for a `shipit.staging.yml` file, and if it doesn't find it it fallbacks to `shipit.yml`

**Comment by teu** [comment]
Is this in the doc though?

**Comment by teu** [comment]
I've added a shipit.production-asg.yml with:

```yml
deploy:
  variables:
    -
      name: FORCE_REBUILD
      title: Force artifacts rebuild
      default: '0'
review:
  checklist:
    - >
    Deployment checklist
    - Tested on pre-production?
    - Is the app stable right now?
```

As I don't see the checklist I gather it is being ignored.
