### ISSUE TITLE
Emergency mode custom command

### ISSUE THREAD

**Issue by teu** [Shopify/shipit-engine#552]
Hi,

we came across a scenario in which it would be extremely useful to have a custom, form input command ran on an emergency action. We had a situation in which we fired up our custom deployments and couldn't roll back due to the cap $ENVIRONMENT deploy:rollback not really meaning anything to our custom capistrano deployment.

Now when we wanted to roll back, shipit loads the specific commit, that as explained before, does not have the override task for reverts, and there is no real clean way to do anything about it.

It would be ideal that in emergency mode, you would be able to hand-fead a command that shipit should run, also would be extremely useful for testing.

**Comment by byroot** [comment]
You can do this with a custom task and env variables:

```yaml
tasks:
  invoke:
    action: "Run arbitrary code"
    steps:
      - '$COMMAND'
    variables:
      name: COMMAND
      title: shell command to execute
```
