### ISSUE TITLE
Predeployment desn't run

### ISSUE THREAD

**Issue by teu** [Shopify/shipit-engine#557]
Hi,

having a problem with predeployment steps:

This is my shipit.yml

```yml
deploy:
  pre:
    - aws autoscaling suspend-processes --auto-scaling-group-name app-asg-001 --scaling-processes ReplaceUnhealthy AZRebalance Launch Terminate ScheduledActions
    - aws autoscaling suspend-processes --auto-scaling-group-name app-shots-asg-001 --scaling-processes ReplaceUnhealthy AZRebalance Launch Terminate ScheduledActions
  post:
    - aws autoscaling resume-processes --auto-scaling-group-name app-asg-001 --scaling-processes ReplaceUnhealthy AZRebalance Launch Terminate ScheduledActions
    - aws autoscaling resume-processes --auto-scaling-group-name app-shots-asg-001 --scaling-processes ReplaceUnhealthy AZRebalance Launch Terminate ScheduledActions

  variables:
    -
      name: FORCE_REBUILD
      title: Force artifacts rebuild (0/1)
      default: '0'
    -
      name: S3_DEPLOYMENT_ONLY
      title: Ignore servers and deploy only to s3 for new machines (0/1)
      default: '0'

rollback:
  pre:
    - aws autoscaling suspend-processes --auto-scaling-group-name app-asg-001 --scaling-processes ReplaceUnhealthy AZRebalance Launch Terminate ScheduledActions
    - aws autoscaling suspend-processes --auto-scaling-group-name app-shots-asg-001 --scaling-processes ReplaceUnhealthy AZRebalance Launch Terminate ScheduledActions
  post:
    - aws autoscaling resume-processes --auto-scaling-group-name app-asg-001 --scaling-processes ReplaceUnhealthy AZRebalance Launch Terminate ScheduledActions
    - aws autoscaling resume-processes --auto-scaling-group-name app-shots-asg-001 --scaling-processes ReplaceUnhealthy AZRebalance Launch Terminate ScheduledActions
  override:
    - cap $ENVIRONMENT deploy
```

The scripts in in "pre" of deployment didn't seem to have been run at all. Am I doing something wrong here?

Also question - will the post onces run on an unsuccesuful deployment?

Thanks

**Comment by byroot** [comment]
> The scripts in in "pre" of deployment didn't seem to have been run at all.

Pre and post steps were added very recently in `0.8.1`. Did you update your shipit install?

> Also question - will the post onces run on an unsuccesuful deployment?

No Shipit will always stop at the first non-zero. The goal of pre and post step is just to avoid committing the deploy steps shipit inferred. For example if you need to compile assets before your cap deploy:

Before you had to do:

```yaml
deploy:
  override:
    - compile-assets
    - cap $ENVIRONMENT deploy
```

While now you can simply do:

```yaml
deploy:
  pre:
    - compile-assets
```
