### ISSUE TITLE
Help writing DRYer shipit.yml file for numerous stacks

### ISSUE THREAD

**Issue by sgringwe** [Shopify/shipit-engine#573]
I have 11 stacks and expect to have more in the future. Right now I have a somewhat verbose shipit.yml file like so:

```
machine:
  environment:
    HEROKU_APP_NAME: custom-staging-name
deploy:
  override:
    - ruby ~/heroku-deploy.rb
rollback:
  override:
    - ruby ~/heroku-rollback.rb
review:
  checklist:
    - Have you proposed the deploy and gotten 'OK' from all committers?
tasks:
  propose:
    action: "Propose Deploy"
    description: "Notifies new commiters in slack that you would like to deploy, and allows QA to be ensured."
    steps:
      - ruby ~/scripts/propose-deploy.rb
  restart:
    action: "Restart App"
    description: "Runs heroku restart for the given app name."
    steps:
      - ruby ~/scripts/heroku-restart.rb
```

Right now, since each stack has a custom HEROKU_APP_NAME env, each stack also has its own shipit.yml file. We use shipit.staging.yml, shipit.production.yml, etc. in each repository.

The problem we are encountering is that the only unique part of these files is the environmental variable, and everything else is the same. This results in lots of repeated shipit files in our repos. Also, I have to update every single repo every time I want to add a new feature to the deployer.

Is there a way to specify a default shipit.yml file in the main deployer app, but still specify machine.environment or other potential specific overrides on a per-stack basis? Or, one step further, the ability to say on a per-stack basis "use the default tasks definition but add this custom task in addition".

Mainly though, I am looking for how to avoid duplicating the same content. Thanks!
