### ISSUE TITLE
Make Kubernetes deploys a first-class citizen

### ISSUE THREAD

**Issue by KnVerey** [Shopify/shipit-engine#632]
Right now, our Kubernetes deploys use an override snippet. That's okay while it's experimental, but won't be great when this is a primary deployment strategy. Currently, the `shipit.yml` for a kube app needs to look like this:

```yaml
deploy:
  override:
    - kubernetes-deploy trashbin tier5

rollback:
  override:
    - kubernetes-deploy trashbin tier5
```

This would be much better:

```yaml
kubernetes:
  namespace: my-app-production
  context: tier4
```

@byroot
cc @Shopify/cloudplatform

**Comment by KnVerey** [comment]
Two caveats related to the WIP nature of our k8s deploys:
* We may also want a third, optional key: `template_dir`. That value is provided as an env override in the current script. The caveat on this is that we're still working out our multi-env template strategy. For example, we may add more sophisticated rendering and have a single directory + `production.yml`, `staging.yml` etc. instead of a directory per env, which would affect this input requirement.

* We _may_ also want to support something along the lines of the following, for weird cases like core that may want to deploy a single env to multiple namespaces (@ibawt):
  ```yaml
  kubernetes:
    - namespace: my-app-production-shardA
      context: tier4
      template_dir: /app/config/deploy/production/shardB/
    - namespace: my-app-production-shardB
      context: tier4
      template_dir: /app/config/deploy/production/shardB/
  ```
  This is **highly** speculative though, so I'd go with what I originally posted unless it would prohibit introducing a variant like the above in the future.
