### ISSUE TITLE
How do I `yarn tag add react-utilities@2.0.0-beta.1 beta` using Shipit?

### ISSUE THREAD

**Issue by kaelig** [Shopify/shipit-engine#735]
My use case is that I'd like to publish a beta to npm and I don't want it to be installed by default when users run `yarn add react-utilities`.

The way I'd publish a version behind a beta flag is:
- version & publish normally
- `yarn tag add react-utilities@2.0.0-beta.1 beta`

I couldn't find how to do this with Shipit - am I missing something?

**Comment by casperisfine** [comment]
Wouldn't this work?

```yaml
deploy:
  post:
    - yarn tag add react-utilities@2.0.0-beta.1 beta
```

(Of course the version part would need to be dynamic, but the idea is there).
