### ISSUE TITLE
Merge Queue Inconsistency/Failure

### ISSUE THREAD

**Issue by tebriel** [Shopify/shipit-engine#796]
I added a PR to the Merge Queue (after enabling it in settings). It showed up on the Merge Queue page immediately. Then I refreshed the page, and the merge queue was back to 0 and my PR was no longer in the merge queue. Additionally sometimes on the Commits and Deploys page, I show `Merge Queue (1)`, other times `Merge Queue (0)`. It is still un-merged, but passing (as seen below). I've added the `shipit.yml` below as well to help debug. There are no error-level logs from either sidekiq or rails.

Here's my `shipit.yml`:
```yaml
deploy:
  override:
    - make deploy
merge:
  require:
    - continuous-integration/jenkins/pr-merge
  ignore:
    - continuous-integration/jenkins/branch
```

After adding by ID
<img width="1163" alt="after adding by id" src="https://user-images.githubusercontent.com/821688/40447194-c8511d40-5e9f-11e8-8013-cd11687696bb.png">

Build Status from Github
<img width="794" alt="Passing Build Status" src="https://user-images.githubusercontent.com/821688/40447005-28b2980e-5e9f-11e8-84a9-73498b3059c3.png">
