### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by gmalette** [Shopify/shipit-engine#80]
Add webhooks to `shipit.yml`

```
webhooks: 
  state_1: 
    - http://webhook1.com/url
  all: 
    - http://webhook2.com/url
```
