### ISSUE TITLE
ActionView::Template::Error in shipit/stacks#show when a bad task is specified in shipit.yml

### ISSUE THREAD

**Issue by mcgain** [Shopify/shipit-engine#862]
in shipit.yml, it's possible to specify a task badly: 
```
tasks:
  reindex:
    action: "Reindex elastic search models"
    description: "Sometimes needed if data changes don't get propogated to Elastic Search."
    title: "Running Procfile command: %{COMMAND}"
    steps:
      - run service-production tier3 $reindex
    variables:
      - name: reindex
        title: "Reindex information for all Elastic Search Models"
```

Note the title mistakenly uses `COMMAND` instead of the intended `reindex` variable.

When this happens, the commit is deployed and the task is saved as a `TaskDefinition` in a `Task`. When the stack#show controller action is called, the `TaskDefinition` title is interpolated and an exception occurs, giving the user a 500. It's then not possible to use the interface to roll back the change.

I fixed the `TaskDefinition` manually, after unsuccessfully manually rolling back the change, but we should prevent this from happening in the first place. 

I'll attempt a fix to just catch the exception and render an error message for the broken task. Ideally we'd validate these tasks and fail CI when an invalid one is specified, but given the frequency of this happening, I don't think it's worth the extra effort.
